### PR TITLE
UMD wrapper

### LINKED ISSUE #309: Trying to load p5 with requirejs
Hello, i need a little bit of help. I am trying to load p5 as a AMD with requirejs. [Code example](https://github.com/visualisierte/middleman-template/blob/backbonejs/source/js/app/main.js)

When i try this, i get the following Errors in the Browser console:
> Uncaught ReferenceError: reqwest is not defined p5.js:2879

The p5 Object is undefined.

Thank you!

### PR DESCRIPTION
**Pull request by brysonian**
Adds UMD wrapper to provide support for build via browserify, commonjs, and amd.

Fixes namespace pollution (reqwest, and a number of variables generated by AMDClean used to be added to window)
To work around a bug in AMDClean, minification is now handled via a separate uglify grunt task.

Should fix #309, #311, and #466.

### CODE REVIEW

**Comment by lmccart** [comment]
woo, looks great, thank you for figuring this out!

**Comment by nasser** [comment]
Nice! Can you update the npm module with the new fixes?

Thanks so much for tackling this!

**Comment by lmccart** [comment]
I think they should be in the newest version (0.3.16) since yesterday, is it not working?

**Comment by nasser** [comment]
My bad, I was testing it incorrectly. Works perfectly! Thanks!

**Pull request merged**
