### PR TITLE
refactor p5.Color

### LINKED ISSUE #537: color() function not working properly in HSB mode
I'm getting a different color with `color()` than with arguments in `fill()` or `background()` directly in HSB mode.

See this example for error:

```
function setup() {
  createCanvas(640, 360);
  colorMode(HSB, 26);
}

function draw() {
  
  if (mouseIsPressed) {
    var c = color(13, 26, 26);
    background(c);
  } else {
    background(13, 26, 26);
  }
}
```

### PR DESCRIPTION
**Pull request by cambridgemike**
I was looking at how p5.Color is implemented and it seems like it could be simplified quite a bit and make better use of Classes. It also fixes  #537. This definitely needs some tests

### CODE REVIEW

**Comment by lmccart** [comment]
thanks!

**Comment by GoToLoop** [comment]
All examples I gave both here & in http://forum.processing.org/two/categories/p5-js stopped working properly after this **p5.Color** huge alteration!

I used arrays to define them like: `const BG   = [0xE0, 0xFF, 0xFF], SOIL = [0x80, 0x50, 0x2A];`
But they stopped working after v0.4.1!  =(

**Comment by cambridgemike** [comment]
Ah, I see, are you then calling color(BG)? I didn't see that method signature documented anywhere, but I can add that back in. Sorry!

**Comment by cambridgemike** [comment]
Do you have a specific example I could test? I believe I fixed this in https://github.com/lmccart/p5.js/pull/541

**Comment by GoToLoop** [comment]
Here's an example. But as I said it affects any sketch using arrays to represent a color:
http://forum.Processing.org/two/discussion/8997/hoppy-beaver

**Comment by cambridgemike** [comment]
Should it look like this? http://cl.ly/image/2w1T1u3F401a 

If so, then the pull request mentioned above #541 fixes the issue.

**Comment by GoToLoop** [comment]
Yea! Those sticks were white/transparent after the modification! Thx for the fix!

**Comment by lmccart** [comment]
I think the array thing was leftover from a while ago.
I can't remember if we had it in there because using that option offers some performance advantage? if not, maybe it's better to just leave it out if it simplifies things and leaves less room for error in keeping the code straight?

**Comment by GoToLoop** [comment]
Actually I've been awaiting for when p5*js would be more flexible to accept a webcode like '#FF0000' as `color` parameter too!

**Comment by kadamwhite** [comment]
@GoToLoop Sounds like a good time for me to try again on #223... @lmccart I've promised to take a look at it before, sorry for being AWOL!

**Pull request merged**
